title: KBase UI
markdown: kramdown
# theme: minima
# remote_theme: pmarsceill/just-the-docs
remote_theme: eapearson/just-the-docs
search_enabled: true
aux_links: 
    "KBase UI on Github":
        - "//github.com/kbase/kbase-ui"
    "About KBase":
        - "//kbase.us/about"