title: KBase UI
remote_theme: eapearson/just-the-docs
search_enabled: false
aux_links: 
    "KBase UI on Github":
        - "//github.com/kbase/kbase-ui"
    "About KBase":
        - "//kbase.us/about"
navigation:
    menu:
        - label: Master
          menu:
            - label: Getting Started
              menu:
                - label: Prerequisites
                - label: Developer Setup
                - label: Quick Start
                - label: Local Dev Prerequisites
                - label: Developer Setup
            - label: Testing
              menu:
                - label: Unit Testing
                - label: Integration Testing
                - label: Image Testing
            - label: Notes
        - label: Develop
        - label: Feature Refactor to CRATS