title: KBase UI
remote_theme: kbaseIncubator/kbase-github-pages-theme
search_enabled: false
#baseurl: /docs
url: ""
description: "Documentation for kbase-ui"
aux_links:
  "KBase UI on Github":
    - "//github.com/kbase/kbase-ui"
  "About KBase":
    - "//www.kbase.us/about"
navigation:
  menu:
#    - label: Index
    - label: Overview
    - label: Design
    - label: Development
    - label: Testing
    - label: Releasing
    - label: Plugins
      menu:
        - label: Updating
        - label: Adding
        - label: Removing
